/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qianxun_kankan_util_VideoProbeUtil */

#ifndef _Included_com_qianxun_kankan_util_VideoProbeUtil
#define _Included_com_qianxun_kankan_util_VideoProbeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qianxun_kankan_util_VideoProbeUtil
 * Method:    readTrackInfo
 * Signature: (Ljava/lang/String;)[Lcom/qianxun/kankan/model/TrackInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qianxun_kankan_util_VideoProbeUtil_readTrackInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_qianxun_kankan_util_VideoProbeUtil
 * Method:    readDuration
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qianxun_kankan_util_VideoProbeUtil_readDuration
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
