/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qianxun_kankan_util_VideoThumbnailerUtil */

#ifndef _Included_com_qianxun_kankan_util_VideoThumbnailerUtil
#define _Included_com_qianxun_kankan_util_VideoThumbnailerUtil
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_qianxun_kankan_util_VideoThumbnailerUtil
 * Method:    generateThumbnail
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qianxun_kankan_util_VideoThumbnailerUtil_generateThumbnail(
		JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
